// 搜索框项目
export const searchItems = [
          { 
        label: "0:使用中，1：未使用",
        value: "status",
        type: "input",
        placeholder: "0:使用中，1：未使用",
        },
              { 
        label: "该设备对应的代理商（用户）ID,默认值为1是小荷用户",
        value: "bindedUserId",
        type: "input",
        placeholder: "该设备对应的代理商（用户）ID,默认值为1是小荷用户",
        },
              { 
        label: "二级代理商Id",
        value: "bindedSubUserId",
        type: "input",
        placeholder: "二级代理商Id",
        },
              { 
        label: "经销商ID（用户Id）",
        value: "userId",
        type: "input",
        placeholder: "经销商ID（用户Id）",
        },
              { 
        label: "方案Id",
        value: "schemaId",
        type: "input",
        placeholder: "方案Id",
        },
              { 
        label: "所属代理商名称",
        value: "brandname",
        type: "input",
        placeholder: "所属代理商名称",
        },
              { 
        label: "",
        value: "deviceId",
        type: "input",
        placeholder: "",
        },
              { 
        label: "备注",
        value: "remark",
        type: "input",
        placeholder: "备注",
        },
              { 
        label: "",
        value: "shakeHandTime",
        type: "input",
        placeholder: "",
        },
              { 
        label: "记录时间",
        value: "updateTime",
        type: "input",
        placeholder: "记录时间",
        },
              { 
        label: "净化前tds 值",
        value: "tds",
        type: "input",
        placeholder: "净化前tds 值",
        },
              { 
        label: "净化前色度",
        value: "color",
        type: "input",
        placeholder: "净化前色度",
        },
              { 
        label: "净化前温度",
        value: "trt",
        type: "input",
        placeholder: "净化前温度",
        },
              { 
        label: "净化前水浊度",
        value: "tbdt",
        type: "input",
        placeholder: "净化前水浊度",
        },
              { 
        label: "净化后的tds",
        value: "purifyTds",
        type: "input",
        placeholder: "净化后的tds",
        },
              { 
        label: "净化后的色度",
        value: "purifyColor",
        type: "input",
        placeholder: "净化后的色度",
        },
              { 
        label: "净化后的温度",
        value: "purifyTrt",
        type: "input",
        placeholder: "净化后的温度",
        },
              { 
        label: "净化后的水浊度",
        value: "purifyTbdt",
        type: "input",
        placeholder: "净化后的水浊度",
        },
              { 
        label: "水量",
        value: "amount",
        type: "input",
        placeholder: "水量",
        },
              { 
        label: "经度",
        value: "lng",
        type: "input",
        placeholder: "经度",
        },
              { 
        label: "纬度",
        value: "lat",
        type: "input",
        placeholder: "纬度",
        },
              { 
        label: "",
        value: "province",
        type: "input",
        placeholder: "",
        },
              { 
        label: "",
        value: "city",
        type: "input",
        placeholder: "",
        },
              { 
        label: "设备别名",
        value: "deviceName",
        type: "input",
        placeholder: "设备别名",
        },
              { 
        label: "区",
        value: "area",
        type: "input",
        placeholder: "区",
        },
              { 
        label: "地址",
        value: "address",
        type: "input",
        placeholder: "地址",
        },
              { 
        label: "",
        value: "customer",
        type: "input",
        placeholder: "",
        },
              { 
        label: "",
        value: "phoneNumber",
        type: "input",
        placeholder: "",
        },
              { 
        label: "机型 ",
        value: "model",
        type: "input",
        placeholder: "机型 ",
        },
              { 
        label: "imei",
        value: "imei",
        type: "input",
        placeholder: "imei",
        },
              { 
        label: "商家",
        value: "merchantName",
        type: "input",
        placeholder: "商家",
        },
              { 
        label: "通道",
        value: "passageId",
        type: "input",
        placeholder: "通道",
        },
              { 
        label: "显示温度",
        value: "showTemp",
        type: "input",
        placeholder: "显示温度",
        },
              { 
        label: "硬件版本",
        value: "hardwareVersion",
        type: "input",
        placeholder: "硬件版本",
        },
    ]

// 功能按钮
export const funcs = ['新增', '修改', '删除'];

// 表格项目
export const tableColumns = [
    { label: "0:使用中，1：未使用", value: "status"},
    { label: "该设备对应的代理商（用户）ID,默认值为1是小荷用户", value: "bindedUserId"},
    { label: "二级代理商Id", value: "bindedSubUserId"},
    { label: "经销商ID（用户Id）", value: "userId"},
    { label: "方案Id", value: "schemaId"},
    { label: "所属代理商名称", value: "brandname"},
    { label: "", value: "deviceId"},
    { label: "备注", value: "remark"},
    { label: "", value: "shakeHandTime"},
    { label: "记录时间", value: "updateTime"},
    { label: "净化前tds 值", value: "tds"},
    { label: "净化前色度", value: "color"},
    { label: "净化前温度", value: "trt"},
    { label: "净化前水浊度", value: "tbdt"},
    { label: "净化后的tds", value: "purifyTds"},
    { label: "净化后的色度", value: "purifyColor"},
    { label: "净化后的温度", value: "purifyTrt"},
    { label: "净化后的水浊度", value: "purifyTbdt"},
    { label: "水量", value: "amount"},
    { label: "经度", value: "lng"},
    { label: "纬度", value: "lat"},
    { label: "", value: "province"},
    { label: "", value: "city"},
    { label: "设备别名", value: "deviceName"},
    { label: "区", value: "area"},
    { label: "地址", value: "address"},
    { label: "", value: "customer"},
    { label: "", value: "phoneNumber"},
    { label: "机型 ", value: "model"},
    { label: "imei", value: "imei"},
    { label: "商家", value: "merchantName"},
    { label: "通道", value: "passageId"},
    { label: "显示温度", value: "showTemp"},
    { label: "硬件版本", value: "hardwareVersion"},
]

