version: '3'
services:
  xplatform-service:
    image: xplatform-service:0.0.1
    container_name: xplatform
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile
    networks:
      - xplat
    ports:
      - 9295:9295
#    volumes:
#linux下校准时间
#      - /etc/timezone:/etc/timezone
#      - /etc/localtime:/etc/localtime
    depends_on:
      - mysql

  nginx:
    image: docker.io/nginx:latest
    container_name: xplatform-nginx-service
    volumes:
      - ./nginx/www:/web
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/log
#linux下校准时间
#      - /etc/timezone:/etc/timezone
#      - /etc/localtime:/etc/localtime
    command: nginx -g "daemon off;"
    networks:
      - xplat
    ports:
      - 8081:81

  mysql:
    image: docker.io/mysql:5.7
    container_name: xplatform-mysql
    restart: always
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M;
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: iswater
      TZ: Asia/Shanghai
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
#linux下校准时间
#      - /etc/timezone:/etc/timezone
#      - /etc/localtime:/etc/localtime
    networks:
      - xplat


networks:
  xplat:
    external: false
